#!/bin/bash

casks=(
    # Browsers
    "google-chrome"
    # IDEs
    "android-studio"
    "visual-studio-code"
    "datagrip"
    # Tools
    "sourcetree"
    "iterm2"
    "postman"
    "evkey"
    "xcodes"
    # Proxy
    "charles"
    # VPN
    "openvpn-connect"
    # Infra
    "vagrant"
    "docker"
    "virtualbox"
    "google-cloud-sdk"
)

packages=(
    # Xcode versions manager
    "xcodesorg/made/xcodes"
    # Version manager
    "rbenv"
    "nvm"
    "pyenv"
    "goenv"
    "fvm"
    # Languages
    "ruby@3.0"
    "node@20"
    "node@16"
    "python@3.9"
    "go@1.21"
    # Database
    "postgresql@16"
    "mysql@8.0"
    "redis@7.2"
    "elastic/tap/elasticsearch-full"
    # Tools
    "tree"
    "alembic"
    # AWS
    "awscli"
    "aws-sam-cli"
    "aws-elasticbeanstalk"
    "aws-amplify"
    "eksctl"
    # GCP
    "cloud-sql-proxy"
    # Infrastructure
    "terraform"
    "terragrunt"
    "ansible"
    "kubectl"
    "helm"
    "minikube"
    "serverless"
)

taps=(
    "hashicorp/tap"
    "leoafarias/fvm"
    "elastic/tap"
)

zshs=(
    "git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git \"\$HOME/.oh-my-zsh\""
    "git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions \${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
    "git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git \${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
)

checkCommand() {
    if ! (type $1 > /dev/null 2>&1); then
        echo "Installing $1"
        return 1
    else
        echo "$1 already installed"
        return 0
    fi
}

checkDirectory() {
    if [ ! -d "$1" ]; then
        echo "Directory $1 does not exist"
        return 1
    else
        echo "Directory $1 already exists"
        return 0
    fi
}

checkFile() {
    if [ ! -f "$1" ]; then
        echo "File $1 does not exist"
        return 1
    else
        echo "File $1 already exists"
        return 0
    fi
}

checkCommand "git" || exit 1
checkCommand "brew" || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

for tap in ${taps[@]}; do
    brew tap $tap
done
brew install --cask "${casks[@]}" --verbose --debug
brew install "${packages[@]}" --verbose --debug

checkDirectory "$HOME/.oh-my-zsh" || for ((i = 0; i < ${#zshs[@]}; i++)); do eval "${zshs[$i]}"; done
checkFile "$HOME/.zshrc" || ln -s "$(pwd)/configs/.zshrc" "$HOME/.zshrc"
checkFile "$HOME/.gitconfig" || ln -s "$(pwd)/configs/.gitconfig" "$HOME/.gitconfig"
