#!/bin/bash

source ./common.sh

# Clean up
dirs=(
    "$HOME/.oh-my-zsh"
    "$HOME/.zshrc"
    "$HOME/.gitconfig"
    "$HOME/.aws"
    "$HOME/.ssh"
    "/etc/apt/sources.list.d"
    "/home/linuxbrew"
)

apts=(
    "git"
    "vim"
    "zsh"
    "curl"
)

snaps=(
    "postman"
)

snaps_classic=(
    "android-studio"
    "code"
    "datagrip"
)

zshs=(
    "git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git \"\$HOME/.oh-my-zsh\""
    "git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions \${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
    "git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git \${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
)

sudo rm -rf "${dirs[@]}"
sudo apt install -y "${apts[@]}"
for ((i = 0; i < ${#snaps[@]}; i++)); do eval sudo snap install "${snaps[$i]}"; done
for ((i = 0; i < ${#snaps_classic[@]}; i++)); do eval sudo snap install "${snaps_classic[$i]}" --classic; done
checkDirectory "$HOME/.oh-my-zsh" || for ((i = 0; i < ${#zshs[@]}; i++)); do eval "${zshs[$i]}"; done
checkFile "$HOME/.zshrc" || ln -s "$(pwd)/configs/.zshrc-ubuntu" "$HOME/.zshrc"
checkFile "$HOME/.gitconfig" || ln -s "$(pwd)/configs/.gitconfig" "$HOME/.gitconfig"