services:
  nginx:
    build:
      context: laravel-nginx-php-fpm-separate/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
      - ./laravel:/var/www/html
    networks:
      - dev-network

  php:
    build:
      context: .
      dockerfile: laravel-nginx-php-fpm-separate/php/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - laravel-vendor:/var/www/html/vendor
      - ./laravel:/var/www/html
      - ./logs:/var/www/html/storage/logs
    networks:
      - dev-network

  mysql:
    image: mysql:8.4.0
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./laravel-nginx-php-fpm-separate/mysql/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 81:80
    depends_on:
      - mysql
    networks:
      - dev-network  

  postgresql:
    image: postgres:16.3
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./laravel-nginx-php-fpm-separate/postgresql/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

  postgresql-admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 82:80
    depends_on:
      - postgresql
    networks:
      - dev-network

  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - dev-network  

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    container_name: redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - dev-network  

volumes:
  mysql-data:
  redis-data:
  postgresql-data:
  pgadmin:
  laravel-vendor:

networks:
  dev-network:
    driver: bridge