services:
  cloud:
    build:
      context: cloud
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app

  nginx:
    image: nginx:1.21.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
    entrypoint: /bin/sh -c "nginx -g 'daemon off;'"

  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb/mysql.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - mysql

  postgresql:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./initdb/postgresql.sql:/docker-entrypoint-initdb.d/init.sql

  postgresql-admin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8081:80
    depends_on:
      - postgresql

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  mysql-data:
  postgresql-data:
  pgadmin:
  redis-data:
  esdata: