services:
  mysql:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    network_mode: "host"
    command: ["mysqld", "--mysql-native-password=ON"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: 172.17.0.1
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql

  postgresql:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    network_mode: "host"

  postgresql-admin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8081:80
    depends_on:
      - postgresql

  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    network_mode: "host"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:172.17.0.1:6379
    ports:
      - 8082:8081
    depends_on:
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    network_mode: "host"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    restart: always
    environment:
      ELASTICSEARCH_URL: http://172.17.0.1:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  mysql-data:
  postgresql-data:
  pgadmin:
  redis-data:
  esdata: