services:
  mysql:
    image: mysql:8.4.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - dev-network  

  postgresql:
    image: postgres:16.3
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./postgresql/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network  

  postgresql-admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 81:80
    depends_on:
      - postgresql
    networks:
      - dev-network  

  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - dev-network  

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    container_name: redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - dev-network  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    restart: always
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    networks:
      - dev-network  

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    restart: always
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - dev-network  

volumes:
  mysql-data:
  postgresql-data:
  pgadmin:
  redis-data:
  esdata:

networks:
  dev-network:
    driver: bridge