tap "hashicorp/tap"
tap "homebrew/bundle"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Terminal multiplexer
brew "tmux"
# UNIX shell (command interpreter)
brew "zsh"
# Terraform
brew "hashicorp/tap/terraform"
# Databases and SQL IDE
cask "datagrip"
# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "google-chrome"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Open-source code editor
cask "visual-studio-code"
