# PostgreSQL configuration
POSTGRES_ADMIN=postgres
POSTGRES_ADMIN_PASSWORD=postgres
POSTGRES_USER=admin
POSTGRES_USER_PASSWORD=admin
POSTGRES_DB_NAME=app

sudo apt install -y postgresql postgresql-contrib

cat > postgresql.sql << EOF
ALTER USER $POSTGRES_ADMIN WITH PASSWORD '$POSTGRES_ADMIN_PASSWORD';
DROP ROLE IF EXISTS $POSTGRES_USER;
CREATE ROLE $POSTGRES_USER WITH LOGIN PASSWORD '$POSTGRES_USER_PASSWORD';
ALTER ROLE $POSTGRES_USER WITH CREATEDB;
DROP DATABASE IF EXISTS $POSTGRES_DB_NAME;
CREATE DATABASE $POSTGRES_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_NAME to $POSTGRES_USER;
EOF

sudo -u postgres psql < postgresql.sql

rm -rf postgresql.sql